version: "3.5"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db:5432/productdb
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=1234
      - QUARKUS_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=productdb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "120MB"

